<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::attempt($this->all('email', 'password'));
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email',
            'password' => 'required',
//            'device_name' => 'required',
        ];
    }

    public function validated()
    {
        return Auth::user()->toArray() +
            ['token' => Auth::user()->createToken('tokens')->plainTextToken]; // TODO: Change the autogenerated stub
    }

}
